---
- hosts: islasgeci
  tasks:
    - name: Configura huso horario
      timezone:
        name: America/Los_Angeles
      become: yes
    - name: Actualiza paquetes del sistema operativo
      apt:
        upgrade: dist
        update_cache: yes
      become: yes
    - name: Instala Docker
      apt:
        name: "docker.io"
        state: present
      become: yes
    - name: Instala Git
      apt:
        name: "git"
        state: present
      become: yes
    - name: Instala Make
      apt:
        name: "make"
        state: present
      become: yes
    - name: Instala pip
      apt:
        name: "python3-pip"
        state: present
      become: yes
    - name: Instala Docker SDK para Python
      pip:
        name: docker
    - name: Prueba Docker
      docker_container:
        name: hello-world
        image: hello-world
